from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from .views import BillUpdate, BillDelete, DeliveryInDelete,DeliveryOutDelete,ClientDelete,Delivery_InUpdate,Delivery_OutUpdate, ClientUpdate
urlpatterns=[

path('',views.index,name='index'),
path('bill_details/', views.bill_details,name='bill_details'),
path('bill_details/<str:bill_id>/', views.bill_details,name='bill_details'),
path('bill_details/<str:bill_id>/<str:status>/', views.bill_details,name='bill_details'),
path('bill_details/<str:bill_id>/<str:status>/<str:date>/', views.bill_details,name='bill_details'),
path('bill_details/<str:bill_id>/<str:status>/<str:date>/<str:category>/', views.bill_details,name='bill_details'),

path('bills/',views.index,name='index'),
path('bills/<str:category>/',views.index,name='index'),
path('bills/<str:category>/<int:year>/<int:month>/<int:day>',views.index,name='index'),
path('bills/<int:year>/<int:month>/<int:day>/',views.index,name='index'),
path('bills/<str:phone>/',views.index,name='index'),
path('bills/<str:category>/<str:phone>/',views.index,name='index'),
path('bills/<str:category>/<int:year>/<int:month>/<int:day>/<str:phone>/',views.index,name='index'),
path('bills/<int:year>/<int:month>/<int:day>/<str:phone>/',views.index,name='index'),

path('add_deliveryout',views.add_deliveryout,name='add_deliveryout'),
path('add_client',views.add_client,name='add_client'),
path('add_deliveryin',views.add_deliveryin,name='add_deliveryin'),
path('add_bill',views.add_bill,name='add_bill'),
path('client_details/<int:pk>/<int:year>/<int:month>/<int:day>/',views.client_details,name='client_details'),
path('client_details/<int:pk>/<int:year>/<int:month>/<int:day>/<int:year_2>/<int:month_2>/<int:day_2>/',views.client_details,name='client_details'),

path('client_details/<int:pk>/<int:year>/<int:month>/<int:day>/<str:bill_id>/<str:operation>/',views.client_details,name='client_details'),
path('client_details/<int:pk>/<int:year>/<int:month>/<int:day>/<int:year_2>/<int:month_2>/<int:day_2>/<str:bill_id>/<str:operation>/',views.client_details,name='client_details'),

path('client_details/<int:pk>/',views.client_details,name='client_details'),
path('delivery_in_details/<int:delivery_in_id>/<int:year>/<int:month>/<int:day>/',views.delivery_in_details,name='delivery_in_details'),
path('delivery_in_details/<int:delivery_in_id>/<int:year>/<int:month>/<int:day>/<str:bill_id>/<str:operation>/',views.delivery_in_details,name='delivery_in_details'),
path('delivery_in_details/<int:delivery_in_id>/',views.delivery_in_details,name='delivery_in_details'),
path('delivery_out_details/<int:delivery_out_id>/<int:year>/<int:month>/<int:day>/',views.delivery_out_details,name='delivery_out_details'),
path('delivery_out_details/<int:delivery_out_id>/<int:year>/<int:month>/<int:day>/<str:bill_id>/<str:operation>/',views.delivery_out_details,name='delivery_out_details'),
path('delivery_out_details/<int:delivery_out_id>/',views.delivery_out_details,name='delivery_out_details'),
path('find_client/',views.find_client, name='find_client'),
path('find_delivery_in/',views.find_delivery_in, name='find_delivery_in'),
path('find_delivery_out/',views.find_delivery_out, name='find_delivery_out'),
path('extract_all_data/<int:year>/<int:month>/<int:day>/', views.extract_all_data,name='extract_all_data'),
path('extract_all_data/', views.extract_all_data,name='extract_all_data'),
path('extract_client_report/<int:pk>/', views.extract_client_report,name='extract_client_report'),
path('extract_delivery_out_report/<str:id>/', views.extract_delivery_out_report,name='extract_delivery_out_report'),
path('extract_all_data_form/',views.request_extract_all_data, name='request_extract_all_data'),
 path('<pk>/updateBill', BillUpdate.as_view(),name="updatebill"),
 path('<pk>/updateDeliveryIn', Delivery_InUpdate.as_view(), name="updatedeliveryin"),
  path('<pk>/updateDeliveryOut', Delivery_OutUpdate.as_view(), name="updatedeliveryout"),
  path('<pk>/updateClient', ClientUpdate.as_view(), name="updateclient"),
 path('<pk>/deleteBill', BillDelete.as_view(),name="deletebill"),
 path('<pk>/deleteDeliveryIn', DeliveryInDelete.as_view(),name="delete_delivery_in"),
 path('<pk>/deleteDeliveryOut', DeliveryOutDelete.as_view(),name="delete_delivery_out"),
 path('<pk>/deleteClient', ClientDelete.as_view(),name="delete_client"),
 path('confirm_delete/', views.deletionComplete, name="confirmDelete"),
# path('extract_system_log/<int:year>/<int:month>/<int:day>/', views.extract_system_log,name='extract_system_log'),
#path('extract_system_log/', views.extract_system_log,name='extract_system_log'),
#path('extract_system_log_form/',views.request_extract_system_log, name='request_extract_system_log'),
#path('viewerlogin/', views.viewer_login, name='viewer_login'),
#path('viewerlogout/', views.viewer_logout, name='viewer_logout'),
#path('viewerlogin/<int:logged_out>/', views.viewer_login, name='viewer_login'),
#path('viewerview/',views.viewer_view,name='viewer_view'),
#path('viewerview/<str:category>/',views.viewer_view,name='viewer_view'),
#path('viewerview/<str:category>/<int:year>/<int:month>/<int:day>',views.viewer_view,name='viewer_view'),
#path('viewerview/<int:year>/<int:month>/<int:day>/',views.viewer_view,name='viewer_view'),
#path('viewerview/<str:phone>/',views.viewer_view,name='viewer_view'),
#path('viewerview/<str:category>/<str:phone>/',views.viewer_view,name='viewer_view'),
#path('viewerview/<str:category>/<int:year>/<int:month>/<int:day>/<str:phone>/',views.viewer_view,name='viewer_view'),
#path('viewer_view/<int:year>/<int:month>/<int:day>/<str:phone>/',views.viewer_view,name='viewer_view'),
]