# Generated by Django 3.2 on 2021-04-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Company', models.CharField(default='', max_length=67111)),
                ('delivery_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.delivery_in')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_Id', models.CharField(max_length=10)),
                ('Date_In', models.DateTimeField(blank=True, null=True, verbose_name='Date In')),
                ('Date_Sent', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Sent')),
                ('Date_Paid', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Paid')),
                ('Date_Done', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Done')),
                ('Done', models.BooleanField(default=False)),
                ('address', models.CharField(default='Address not found', max_length=100000)),
                ('directions', models.CharField(blank=True, default='', max_length=100000)),
                ('endClientName', models.CharField(default='Unknown Name', max_length=100000)),
                ('endClientNumber', models.CharField(default='03000000', max_length=10000)),
                ('Product_cost', models.IntegerField(default=0)),
                ('Currency', models.CharField(choices=[('usd', 'USD'), ('lbp', 'LBP')], default='lbp', max_length=10)),
                ('Delivery_cost', models.IntegerField(default=0)),
                ('Status', models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('sent', 'SENT'), ('refunded', 'REFUNDED')], default='pending', max_length=99)),
                ('Hidden_Status', models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('sent', 'SENT'), ('refunded', 'REFUNDED')], default='pending', max_length=99)),
                ('Done_Refunding', models.BooleanField(default=False)),
                ('Extracted_For_DelOut', models.BooleanField(default=False)),
                ('Notes', models.CharField(blank=True, default='', max_length=10000)),
                ('Hidden_Id', models.CharField(max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.client')),
                ('delivery_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.delivery_in')),
                ('delivery_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryApp.delivery_out')),
            ],
        ),
    ]
