# Generated by Django 3.2 on 2021-04-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Bill_Id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
