# Generated by Django 3.2 on 2021-04-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0002_alter_bill_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Company',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
